### ISSUE TITLE
sPyNNaker 1!4.0.1 incompatibility with SpiNNFrontEndCommon 1!5.0.0

### ISSUE THREAD

**Issue by marco-monforte** [SpiNNakerManchester/SupportScripts#20]
Hello!

I've updated all my folders to the latest commits but, once I try to run the setup.sh, I get the following error:

Installed /home/mmonforte/spiNNaker/sPyNNaker
Processing dependencies for sPyNNaker==1!4.0.1
Searching for SpiNNFrontEndCommon<1!5.0.0,>=1!4.0.1
Reading https://pypi.org/simple/SpiNNFrontEndCommon/
No local packages or working download links found for SpiNNFrontEndCommon<1!5.0.0,>=1!4.0.1
error: Could not find suitable distribution for Requirement.parse('SpiNNFrontEndCommon<1!5.0.0,>=1!4.0.1')
./SupportScripts/setup.sh: line 10: exit: sPyNNaker: numeric argument required

While my pip list says:

SpiNNFrontEndCommon           1!5.0.1     /home/mmonforte/spiNNaker/SpiNNFrontEndCommon       

So, SpiNNFrontEndCommon has been updated to the 1!5.0.1 version, but sPyNNaker is looking only for previous ones. What should I do?

Thanks

**Comment by Christian-B** [comment]
Please update spynakker again as this has now been resolved there.

**Comment by marco-monforte** [comment]
Hi Christian, thanks for the help but nothing changed. I don't even see any new commit in sPyNNaker (master branch).

**Comment by Christian-B** [comment]
If you are getting "Processing dependencies for sPyNNaker==1!4.0.1"
Then you are NOT on the latest branch of sPYNNaker as show here that is at 1!5.0,.1
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/_version.py

(Or there is an older version of SpyNNaker floating around somewhere in your lib folders)

And Spynnaker8 requires that as shown in 
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/setup.py
and
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/requirements.txt

We also have integration tests which run every night which start with full downloads and they are clearly able to build.

**Comment by marco-monforte** [comment]
Sorry, it seemed that sPyNNaker8 wasn't updated to the 1!5 version, sPyNNaker instead was. Now everything compiles!

Thanks a lot
