### ISSUE TITLE
Error in setup.sh and setup_sudo.sh

### ISSUE THREAD

**Issue by DennisZemela** [SpiNNakerManchester/SupportScripts#22]
Hello

Today I installed the SpiNNaker Software on my Laptop with the latest versions from the git-repositories. Unfortunately the setup.sh and the setup_sudo.sh scripts did not work giving me the following error:

  _File "setup.sh", line 4
    do_setup() {
               ^
SyntaxError: invalid syntax_

Removing the semicolon after Conda_Prefix in line 7 solved the problem:

        if [ -z "$VIRTUAL_ENV" ] && [ -z "$CONDA_PREFIX" ]; && [ -z "$ASROOT" ]; then

Best regards
Dennis

**Comment by andrewgait** [comment]
Hi Dennis,

Have fixed setup.sh in https://github.com/SpiNNakerManchester/SupportScripts/pull/23 - as far as I can see, setup_sudo.sh is working, though - did you get an error there too?

**Comment by DennisZemela** [comment]
Hello Andrew

I'm sorry, I meant the setup_install.sh script instead of the setup_sudo.sh.
I was not checking the setup_sudo.sh then.

Thank you for handling the issue

**Comment by andrewgait** [comment]
Hi Dennis - thanks, missed that one as well, have fixed it now (NB: committed straight to master).
