### ISSUE TITLE
gitclone.sh can not handle repositories with main instead of master

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SupportScripts#28]
To replicate
Delete the branch
https://github.com/SpiNNakerManchester/TestBase/tree/master

run git actions in https://github.com/SpiNNakerManchester/sPyNNaker

**Comment by dkfellows** [comment]
Is this still an issue?

**Comment by Christian-B** [comment]
TestBase no longer has a master branch and gitclone.sh works fine
