### ISSUE TITLE
Out of date make script?

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/SupportScripts#35]
Does anyone know if anyone is using https://github.com/SpiNNakerManchester/SupportScripts/blob/master/automatic_spinnaker_make.sh at the moment?  If not I suggest deleting it; if yes then I think it's out of date...

**Comment by dkfellows** [comment]
I've never used it.

**Comment by Christian-B** [comment]
I vote delete!

**Comment by rowleya** [comment]
Also agree that deletion is fine by me
